### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by atenart**

### CODE REVIEW

**Review by vlrpl — COMMENTED** [review]
shouldn't the doc be updated as well?

**Comment by atenart** [comment]
> shouldn't the doc be updated as well?

The README is updated in this PR too. Are you thinking about something else?

**Comment by vlrpl** [comment]
> > shouldn't the doc be updated as well?
> 
> The README is updated in this PR too. Are you thinking about something else?

yes, I was thinking that I needed some coffee and the PR is fine :)

**Review by vlrpl — APPROVED** [review]
lgtm!

**Pull request merged**
